[package]
name = "ani-dl"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
inquire = "*"
colored = "*"
spinners = "*"
titlecase = "*"
