[package]
name = "ani-dl"
version = "1.3.0"
edition = "2021"
license-file = "LICENSE"
description = "Download and watch animes in VF and VOSTFR (aka french versions)"
repository = "https://github.com/B0SEmc/ani-dl"
readme = "README.md"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
inquire = "0.7.5"
colored = "2.1.0"
spinners = "4.1.1"
titlecase = "3.2.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
directories = "5.0.1"
threadpool = "1.8.1"
